# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiliTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_id', models.IntegerField(unique=True)),
                ('typeid', models.IntegerField(null=True)),
                ('ctime', models.DateTimeField()),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiliTagData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.IntegerField(null=True)),
                ('atten', models.IntegerField(null=True)),
                ('is_atten', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('hates', models.IntegerField(null=True)),
                ('attribute', models.IntegerField(null=True)),
                ('liked', models.IntegerField(null=True)),
                ('hated', models.IntegerField(null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagdata', to='bilibili.BiliTag', to_field='tag_id')),
            ],
        ),
        migrations.CreateModel(
            name='BiliUper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.IntegerField(unique=True)),
                ('sign', models.CharField(max_length=255, null=True)),
                ('regtime', models.DateTimeField()),
                ('createtime', models.DateTimeField()),
                ('avatar', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiliUperData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videonum', models.IntegerField(default=0, null=True)),
                ('gz', models.IntegerField(default=0, null=True)),
                ('fans', models.IntegerField(default=0, null=True)),
                ('play', models.IntegerField(default=0, null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('fans_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('uper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uperdata', to='bilibili.BiliUper', to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='BiliVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True, verbose_name='avid')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField()),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('vdesc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiliVideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(null=True, verbose_name='view num')),
                ('danmaku', models.IntegerField(null=True, verbose_name='danmu num')),
                ('reply', models.IntegerField(null=True, verbose_name='reply num')),
                ('favorite', models.IntegerField(null=True)),
                ('coin', models.IntegerField(null=True)),
                ('share', models.IntegerField(null=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videodata', to='bilibili.BiliVideo', to_field='aid')),
            ],
        ),
        migrations.CreateModel(
            name='BiliVideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagvideos', to='bilibili.BiliTag', to_field='tag_id')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videotags', to='bilibili.BiliVideo', to_field='aid')),
            ],
        ),
        migrations.AddField(
            model_name='bilivideo',
            name='tags',
            field=models.ManyToManyField(related_name='video', through='bilibili.BiliVideoTag', to='bilibili.BiliTag'),
        ),
        migrations.AddField(
            model_name='bilivideo',
            name='uper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='bilibili.BiliUper', to_field='uid'),
        ),
    ]
