# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('bg_img_url', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_actor', models.CharField(blank=True, max_length=255, null=True)),
                ('from_at', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('op_type', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_type', models.IntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=255, null=True)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(to='movies.MovieTags'),
        ),
    ]
