# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='film_type',
            field=models.IntegerField(choices=[(0, 'whole film'), (1, 'Trailer')], default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[(0, 'youku')], default=0, null=True),
        ),
    ]
