# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170827_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('seq', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.IntegerField(choices=[(0, b'\xe7\x94\xb5\xe5\xbd\xb1'), (1, b'\xe5\x89\xa7\xe9\x9b\x86'), (2, b'\xe7\xbb\xbc\xe8\x89\xba'), (3, b'\xe5\x8d\xa1\xe9\x80\x9a')], default=0),
        ),
        migrations.AddField(
            model_name='submovies',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='movies.Movies'),
        ),
    ]
